# This is a basic workflow to help you get started with Actions

name: Test addon and create zip

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "web-ext lint"
      uses: kewisch/action-web-ext@v1.0
      with:
        cmd: lint
        channel: listed
